### ISSUE TITLE
Memory usage example does not work (t3.6)

### ISSUE THREAD

**Issue by crteensy** [duff2013/Zilch#1]
When I compile the memory usage example for the teensy 3.6 and download it, USB Serial is not available and I can't see any results.

**Comment by duff2013** [comment]
Strange I just used on my 3.6, use the Serial Plotter also.

**Comment by crteensy** [comment]
I tried again:
- Examples->Zilch->memory_layout, compile and upload
- Tools->Port is grayed out
- Serial Monitor shows Teensy as "Offline" in title bar
- Serial Plotter shows an error message: "Board at /dev/ttyACM0 is not available"
- Teensy can only be reprogrammed by pushing the program button
I'm using Arduino 1.8.4. Other sketches that use Serial work just fine.

**Comment by crteensy** [comment]
Is it possible that you made some changes locally that are not yet pushed to github?

**Comment by duff2013** [comment]
I'll check, what speed and optimization levels are you using?

**Comment by crteensy** [comment]
180 MHz, "Faster"

**Comment by duff2013** [comment]
Just updated the library and tried the memory layout example on the 3.6/Faster/180MHz and it works for me.

**Comment by crteensy** [comment]
Still doesn't work for me. I downloaded a fresh copy of the library, restarted arduino, replugged the Teensy - no luck. It might be my hardware then, or something totally different.

Same observations on a Teensy 3.2, 72 MHz, Faster!

**Comment by duff2013** [comment]
Maybe try to increase the stack sizes, and what version of Teensyduino are you using, I'm using 1.38 beta2.

**Comment by crteensy** [comment]
Teensyduino 1.39 release. I can't try it right now with increased stack sizes but I'll get back to it later today

**Comment by duff2013** [comment]
I can confirm Teensyduino 1.39 breaks Zilch! I have to see what changed since 1.38 beta2. Kind of annoying!

**Comment by crteensy** [comment]
funky: the simple Zilch example doesn't work either, but a sketch I wrote myself *does*. I even doubled the stack size in the simple example. Both the simple example and my sketch use AllocateMemoryPool(), task.create() and task.begin().

**Comment by crteensy** [comment]
it's really obscure. I now use freeMemory() in my application and it works as intended. It's just the examples that don't run.

**Comment by duff2013** [comment]
I think its all this event stuff paul added to the core which should be a library that gets added if I want it, now I have figure out some work around.

**Comment by crteensy** [comment]
Yes there was a discussion about yield() which might be relevant but I wasn't sure

**Comment by duff2013** [comment]
It was that yield problem, looks like paul going to have fix soon. But if you want to fix it now, FrankB's [patch works](https://github.com/PaulStoffregen/cores/pull/254/commits/31bdbb1261565a9a253ab612057812ffca05a6cf).

**Comment by duff2013** [comment]
Pauls [patch](https://github.com/PaulStoffregen/cores/commit/2d7cf7acddd4d2d5fcf7e13fe98c3f8b8151bf81) works and easier fix:)

**Comment by crteensy** [comment]
With the linked patch applied it works on T3.6 (memory layout example, simple example and own sketch).
